In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn 

In [9]:
pip install --upgrade pip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 14.7 MB/s eta 0:00:00m eta 0:00:010:00:01
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Note: you may need to restart the kernel to use updated packages.


In [8]:
!pip install sklearn

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://g

In [11]:
'pip install scikit-learn'

'pip install scikit-learn'

In [13]:
pip install scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 52.6 MB/s eta 0:00:00 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.6/25.6 MB 65.5 MB/s eta 0:00:00 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
ls ml

11th aug.ipynb              dummy.txt
12th aug_lambda.ipynb       example.ipynb
12thaug11.ipynb             exceptional_handling.ipynb
13th aug.ipynb              exe2.ipynb
14th aug.ipynb              execrcise.ipynb
22aug_ml.ipynb              hello.py
24thaug.ipynb               indexofbook.ipynb
3rd aug.ipynb               loop.ipynb
4thsep.ipynb                my_files_ml/
6th aug.ipynb               num_def.csv
6thaug_imp.ipynb            operations.ipynb
7th aug.ipynb               output.csv
Data types.ipynb            preparation.ipynb
EasyVisa.csv                session. 4.ipynb
ML-cls1.ipynb               session1.ipynb
ML.ipynb                    session2 variables.ipynb
Untitled.ipynb              session3print.ipynb
aug23_cat_anlalysy.ipynb    string_examples.ipynb
aug8.ipynb                  test_lAUu6dG.csv
bank.csv                    wine.csv
cont_pic.png                works/


In [10]:
file='/Users/vijayasri/ML/EasyVisa.csv'
visa_df=pd.read_csv(file)
visa_df

case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N   
1         EZYV02      Asia              Master's                  Y   
2         EZYV03      Asia            Bachelor's                  N   
3         EZYV04      Asia            Bachelor's                  N   
4         EZYV05    Africa              Master's                  Y   
...          ...       ...                   ...                ...   
25475  EZYV25476      Asia            Bachelor's                  Y   
25476  EZYV25477      Asia           High School                  Y   
25477  EZYV25478      Asia              Master's                  Y   
25478  EZYV25479      Asia              Master's                  Y   
25479  EZYV25480      Asia            Bachelor's                  Y   

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007   
1                         N             2412         2002   
2                         Y            44444         2008   
3                         N               98         1897   
4                         N             1082         2005   
...                     ...              ...          ...   
25475                     Y             2601         2008   
25476                     N             3274         2006   
25477                     N             1121         1910   
25478                     Y             1918         1887   
25479                     N             3195         1960   

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y   
1                Northeast       83425.6500         Year                  Y   
2                     West      122996.8600         Year                  Y   
3                     West       83434.0300         Year                  Y   
4                    South      149907.3900         Year                  Y   
...                    ...              ...          ...                ...   
25475                South       77092.5700         Year                  Y   
25476            Northeast      279174.7900         Year                  Y   
25477                South      146298.8500         Year                  N   
25478                 West       86154.7700         Year                  Y   
25479              Midwest       70876.9100         Year                  Y   

      case_status  
0          Denied  
1       Certified  
2          Denied  
3          Denied  
4       Certified  
...           ...  
25475   Certified  
25476   Certified  
25477   Certified  
25478   Certified  
25479   Certified  

[25480 rows x 12 columns]

In [16]:
visa_df['case_status']=='certified'
np.where(visa_df['case_status']=='certified',1,0)


array([0, 0, 0, ..., 0, 0, 0])

In [18]:
one-hot-encoder
1.one hot enoder means at a time only one will be ON, other is OFF
2.one hotb encoder creats a new extra coloumn base on labels in the column
3.if you apply one hot encoder on case_STATUS IT CREATES TWO EXTRA COLUMNS
*case_status_certified
*case_status_denied
|case_status|case_status_denied|case_status_certified|
|-----------|------------------|---------------------|
|denied     |        1         |       0             |
|certified  |        0         |       1             |

SyntaxError: invalid decimal literal (681230368.py, line 2)

In [ ]:
advantages of one hot encoder
*independency between th variables
*one of the important property before apply ml models
*varabiles are independent or orthogonal or perpendicular each other 


In [4]:
file='/Users/vijayasri/ML/EasyVisa.csv'
visa_df=pd.read_csv(file)
visa_df.drop('case_id',axis=1,inplace=True)
pd.get_dummies(visa_df,dtype='int')


FileNotFoundError: [Errno 2] No such file or directory: '/Users/vijayasri/ML/EasyVisa.csv'

In [ ]:
label encoder

In [17]:
file='/Users/vijayasri/ML/EasyVisa.csv'
visa_df=pd.read_csv(file)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['continent'])[:10]

array([1, 1, 1, 1, 0, 1, 1, 3, 1, 2])

In [27]:
file='/Users/vijayasri/ML/EasyVisa.csv'
visa_df=pd.read_csv(file)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['case_status'])[:10]

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 0])

In [7]:
file='/Users/vijayasri/ML/EasyVisa.csv'
visa_df=pd.read_csv(file)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['prevailing_wage'])[:10]


FileNotFoundError: [Errno 2] No such file or directory: '/Users/vijayasri/ML/EasyVisa.csv'

In [32]:
file='/Users/vijayasri/ML/EasyVisa.csv'
visa_df=pd.read_csv(file)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cat_cols=visa_df.select_dtypes(include='object')
for i in cat_cols:
    visa_df[i]=le.fit_transform(visa_df[i])

visa_df

case_id  continent  education_of_employee  has_job_experience  \
0            0          1                      2                   0   
1            1          1                      3                   1   
2            2          1                      0                   0   
3            3          1                      0                   0   
4            4          0                      3                   1   
...        ...        ...                    ...                 ...   
25475    17204          1                      0                   1   
25476    17205          1                      2                   1   
25477    17206          1                      3                   1   
25478    17207          1                      3                   1   
25479    17209          1                      0                   1   

       requires_job_training  no_of_employees  yr_of_estab  \
0                          0            14513         2007   
1                          0             2412         2002   
2                          1            44444         2008   
3                          0               98         1897   
4                          0             1082         2005   
...                      ...              ...          ...   
25475                      1             2601         2008   
25476                      0             3274         2006   
25477                      0             1121         1910   
25478                      1             1918         1887   
25479                      0             3195         1960   

       region_of_employment  prevailing_wage  unit_of_wage  \
0                         4         592.2029             0   
1                         2       83425.6500             3   
2                         4      122996.8600             3   
3                         4       83434.0300             3   
4                         3      149907.3900             3   
...                     ...              ...           ...   
25475                     3       77092.5700             3   
25476                     2      279174.7900             3   
25477                     3      146298.8500             3   
25478                     4       86154.7700             3   
25479                     1       70876.9100             3   

       full_time_position  case_status  
0                       1            1  
1                       1            0  
2                       1            1  
3                       1            1  
4                       1            0  
...                   ...          ...  
25475                   1            0  
25476                   1            0  
25477                   0            0  
25478                   1            0  
25479                   1            0  

[25480 rows x 12 columns]

In [33]:
visa_df['case_status']
le.inverse_transform(visa_df['case_status'])

array(['Denied', 'Certified', 'Denied', ..., 'Certified', 'Certified',
       'Certified'], dtype=object)

In [ ]:
map
np.where
one hot encoder ==pg.getdummies
labelEncoder sklearn